version: 2
jobs:
  build:
    working_directoyr: ~/
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: sudo python setup.py install
      - run:
          command: python tests/test.py